[2024-04-08T06:26:36.273+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.get_name manual__2024-04-08T06:26:35.447859+00:00 [queued]>
[2024-04-08T06:26:36.282+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.get_name manual__2024-04-08T06:26:35.447859+00:00 [queued]>
[2024-04-08T06:26:36.283+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-04-08T06:26:36.283+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2024-04-08T06:26:36.283+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-04-08T06:26:36.297+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_name> on 2024-04-08 06:26:35.447859+00:00
[2024-04-08T06:26:36.301+0000] {standard_task_runner.py:55} INFO - Started process 21224 to run task
[2024-04-08T06:26:36.303+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v04', 'get_name', 'manual__2024-04-08T06:26:35.447859+00:00', '--job-id', '1512', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp15wms9ru']
[2024-04-08T06:26:36.304+0000] {standard_task_runner.py:83} INFO - Job 1512: Subtask get_name
[2024-04-08T06:26:36.358+0000] {task_command.py:388} INFO - Running <TaskInstance: our_dag_with_python_operator_v04.get_name manual__2024-04-08T06:26:35.447859+00:00 [running]> on host 3dc1147ef06e
[2024-04-08T06:26:36.422+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=jiseungmin
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2024-04-08T06:26:35.447859+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-08T06:26:35.447859+00:00
[2024-04-08T06:26:36.423+0000] {python.py:177} INFO - Done. Returned value was: Jerry
[2024-04-08T06:26:36.442+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v04, task_id=get_name, execution_date=20240408T062635, start_date=20240408T062636, end_date=20240408T062636
[2024-04-08T06:26:36.475+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-04-08T06:26:36.493+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
